### ISSUE TITLE
Explore angular build using github pages https://angular.io/guide/deployment

### ISSUE THREAD

**Issue by mathewjustin** [OpenExpress/openexpress.in#1]
Create a sample angular project and serve components statically. Without using ng serve. This will help us to build github pages and link to actual website

**Comment by mathewjustin** [comment]
@vivek02912018 aliyo vallom nadakkuvo

**Comment by vivek02912018** [comment]
nadathan nokkuva aliya

**Comment by mathewjustin** [comment]
Already merged
